---
name: Action

on:
  pull_request:
    paths-ignore:
      - '*.md'
  push:
    paths-ignore:
      - '*.md'

jobs:
  Convert:
    runs-on: windows-latest
    steps:
      - name: FX Data Convert Action
        uses: FX31337/FX-Data-Convert-Action@v1.0.0
            InputFile: 'myfile.csv'
            OutputFormat: 'fxt'
